# Generated by Django 4.2.30 on 2026-07-07 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_gameresult_started_at_ms_alter_gameresult_room_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'easy'), ('medium', 'medium'), ('hard', 'hard')], default='medium', max_length=10),
        ),
    ]
