# Generated by Django 4.2.30 on 2026-07-07 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_room_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tier',
            field=models.CharField(choices=[('iron', 'iron'), ('bronze', 'bronze'), ('silver', 'silver'), ('gold', 'gold'), ('platinum', 'platinum'), ('diamond', 'diamond'), ('challenger', 'challenger')], default='iron', max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='tier_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='is_ranked',
            field=models.BooleanField(default=False),
        ),
    ]
