# Generated by Django 4.2.30 on 2026-07-07 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_profile_tier_profile_tier_score_room_is_ranked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='difficulty',
        ),
    ]
