# Generated by Django 4.2.30 on 2026-07-08 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_remove_room_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='codesnippet',
            name='pool',
            field=models.CharField(choices=[('match', '실전(친선전/랭킹전)'), ('practice', '연습')], default='match', max_length=10),
        ),
    ]
